//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelNo { get; set; }
        public string PAdSoyad { get; set; }
        public Nullable<int> PYas { get; set; }
        public Nullable<int> PTelefon { get; set; }
        public byte[] PAdres { get; set; }
    }
}
