//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonelNo { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelTc { get; set; }
        public string PersonelAdres { get; set; }
        public Nullable<decimal> PersonelMaas { get; set; }
        public Nullable<int> SubeNo { get; set; }
    
        public virtual Subeler Subeler { get; set; }
    }
}
